name: Galio Framework
version: 1.0.0
description: Build better apps using React Native
website_url: https://galio.io/
github_url: https://github.com/galio-org/galio
docs_url: https://galio.io/docs/#/install
keywords: galio, mobile framework, android react native, ios react native, free mobile framework, react native, free react native, open source react native, mit license, mobile app, react native, react native app, react native android, react native github, react native ios, react native ui, react native documentation, react native facebook, facebook react native, react native framework, react native themes, react native showcase, react native dropdown, react native radio button, react native progress bar, react native search bar, react android, react native examples, react native forms, react native application, react native code, react native js, about galio, galio presentation, galio components, galio application, galio radio button, galio progress bar, galio search bar
discord_link: https://discordapp.com/invite/EwmQBxS

twitter_handle: galio
facebook_handle: galio
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
