import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Get Started',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Learn how to install and set up Galio Framework',
        slug: 'get-started',
      },
      // Custom order: list docs explicitly in the exact order you want them to appear
      items: [
        'get-started/install',
        'get-started/theme-galio',
        'get-started/light-dark-mode',
        'get-started/modern-usage',
      ],
    },
    {
      type: 'category',
      label: 'Components',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Explore the wide range of UI components offered by Galio',
        slug: 'components',
      },
     
      items: [
        {
          type: 'autogenerated',
          dirName: 'components', // Generate sidebar slice from docs/components (or 'shared' or 'features')
        },
      ],
    },
    {
      type: 'category',
      label: 'Plugins',
      collapsed: false,
      link: {
        type: 'generated-index',
        description: 'Extend Galio functionality with plugins',
        slug: 'plugins',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'plugins', // Generate sidebar slice from docs/plugins (or 'shared' or 'features')
        },
      ],
    },
    'contributing',
  ],
};

export default sidebars;
